sudo: required
services:
    - docker

before_install:
    - docker build -t fusionproj1989/docker-react -f Dockerfile.dev .

script:
    - docker run fusionproj1989/docker-react npm run test -- --coverage